---
- name: Print linux distribution and version
  hosts: all

  tasks:
    - name: capture output of id command
      command: cat /etc/os-release
      register: login
    - debug: msg="{{ login.stdout }}"

    - name: capture output of /etc/motd
      command: dpkg -l ubuntu-desktop
      register: login
      when: ansible_distribution == "Ubuntu"
    - debug: msg="{{ login.stdout }}"
