- name: source_dotfiles
  # change owner and group on directory dev
  file:
    owner: klaseh
    group: klaseh
    path: /home/klaseh/dev
  notify: source_dotfiles1

- name: source_dotfiles1
  # change owner and group on directory dev/dotfiles
  file:
    owner: klaseh
    group: klaseh
    path: /home/klaseh/dev/dotfiles
    recurse: yes
  notify: source_dotfiles2

- name: source_dotfiles2
  #Execute the bootstrap
  shell: set -- -f ; source /home/klaseh/dev/dotfiles/bootstrap.sh && echo "Done" > /dev/null
  args:
    executable: sudo -u klaseh  /bin/bash

- name: mount_all
  become_user: root
  shell: mount -a
  args:
    executable: /bin/bash
