- name: install unzip
  package:
    name: unzip

- name: install command line apps
  apt:
    pkg:
    - git
    - ansible
    - aria2
    - fdupes
    - parallel
    - tmux
    - python3-pip
    - curl
    - rename
    state: latest

- name: install python packages
  pip:
    name:
      - topalias
      - bpytop
      - youtube-dl
    state: latest

- name: install graphic apps
  apt:
    pkg:
    - meld
    - vlc
    - klatexformula
    - regexxer
    - keepassxc
    state: latest

- name: Add Key form atom editor
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    state: present

- name: Add repo for atom editor
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    filename: AtomEditor_atom

- name: Install atom editor
  apt:
    pkg:
    - atom
    state: latest


- name: Checkout blueslow's dotfiles
  become_user: klaseh
  ansible.builtin.git:
    repo: https://github.com/blueslow/dotfiles.git
    dest: /home/klaseh/dev/dotfiles
    clone: true
  notify: source_dotfiles

- name: create klaseh .creds directory
  file:
    path: /home/klaseh/.creds
    state: directory
    owner: klaseh
    group: klaseh
    mode: 0700

- name: copy klaseh cred files
  copy:
    src: /home/klaseh/.ssh/creds/
    dest: /home/klaseh/.creds/
    owner: klaseh
    group: klaseh
    mode: 0600

- name: create /media/klaseh  directory
  file:
    path: /media/klaseh
    state: directory
    owner: klaseh
    group: klaseh
    mode: 0700

- name: create /media/shared  directory
  file:
    path: /media/shared
    state: directory
    owner: klaseh
    group: klaseh
    mode: 0775
#
# - name: change /etc/fstab
#   lineinfile:
#     path: /etc/fstab
#     regexp: '^//192.168.10.1/klaseh'
#     line: "//192.168.10.1/klaseh	/media/klaseh	cifs credentials=/home/klaseh/.creds/condor_klaseh,iocharset=utf8,uid=klaseh,gid=klaseh 0 0"
#   notify: mount_all
#

- name: Mount klaseh share
  mount:
    path: /media/klaseh
    src: //192.168.10.1/klaseh
    fstype: cifs
    opts: credentials=/home/klaseh/.creds/condor_klaseh,iocharset=utf8,uid=klaseh,gid=klaseh
    state: present

- name: Mount shared share
  mount:
    path: /media/shared
    src: //192.168.10.1/shared
    fstype: cifs
    opts: credentials=/home/klaseh/.creds/condor_klaseh,iocharset=utf8,uid=klaseh,gid=klaseh
    state: present
