- name: Add repo for atom editor
  tags: tstat
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    filename: atom.list

- name: install unzip
  tags: tstat
  package:
    name: unzip

- name: install command line apps
  tags: tstat
  apt:
    pkg:
    - git
    - ansible
    - aria2
    - fdupes
    - parallel
    - tmux
    - python3-pip
    - curl
    state: latest

- name: install python packages
  tags: tstat
  pip:
    name:
      - topalias
      - bpytop
      - youtube-dl
    state: latest

- name: install graphic apps
  tags: tstat
  apt:
    pkg:
    - meld
    - vlc
    - klatexformula
    - regexxer
    - keepassxc
    - atom
    state: latest

- name: Checkout blueslow's dotfiles
  tags: tstat
  become_user: klaseh
  ansible.builtin.git:
    repo: https://github.com/blueslow/dotfiles.git
    dest: /home/klaseh/dev/dotfiles
    clone: true
  notify: source_dotfiles
