- name: install unzip
  tags: tstat
  package:
    name: unzip

- name: install command line apps
  tags: tstat
  apt:
    pkg:
    - git
    - ansible
    - aria2
    - fdupes
    - parallel
    - tmux
    - pyhton3-pip
    state: latest

- name: install python packages
  tags: tstat
  pip:
    name:
      - topalias

- name: install graphic apps
  tags: tstat
  apt:
    pkg:
    - meld
    - vlc
    - klatexformula
    - regexxer
    - keepassxc
    state: latest

- name: Checkout blueslow's dotfiles
  tags: tstat
  become_user: klaseh
  ansible.builtin.git:
    repo: https://github.com/blueslow/dotfiles.git
    dest: /home/klaseh/dev/dotfiles
    clone: true
  notify: source_dotfiles
