- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIETTCApxalcbRpLDwJoOPM5jr7E/ojBPJyVqdIdrJ66E ansible"

- name: add ssh key for klaseh
  authorized_key:
    user: klaseh
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE3ShmhSX1HEdvhqP5khdZRW8vc2yUl655er/RTaiIsp klaseh@nimbus104"

- name: add ssh key for klaseh at hustkvarna
  authorized_key:
    user: klaseh
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAder1mhDPrA4S1hvVqoWgqTgzYUEVzeWGNqqSBU3e7H klaseh2@huskvarna.sehlstedt.se"



- name: generate sshd_config file from templates
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
